#!/usr/bin/env node

/*
 * CtTool
 * Desc: Searches Certificate Transparency services for hostnames linked to certificates.
 * Author: Carey Li (https://github.com/cry)
 */

 "use strict";

let googleCT = require("./lib/ct/googleCT.js"),
	program = require('commander'),
	Promise = require('bluebird'),
	fs = Promise.promisifyAll(require('fs')),
	log = (require('log4js')).getLogger('Main');

log.info("Certificate Transparency tool v0.0.1");
log.warn("Note: Currently only searches Google CT logs, will add Symantic CT logs eventually.\n");

program
	.version('0.0.1')
	.option('-c, --ct-server <server>', 'specify which ct service to use (default Google)')
	.option('-f, --file (file)', 'save hostnames to file as JSON [res.json]', 'res.json');

program
	.command('discover <hostname>')
	.description('scan Certificate Transparency logs for subdomains of hostname')
	.action((hostname) => {
		googleCT.getHostnames(hostname)
			.then((res) => {
				console.log();
				log.info("Unique hostnames found: \n");

				res.forEach((el) => console.log("> " + el));

				console.log();

				if (program.file !== undefined) {
					fs.writeFile(program.file, res);
				};
			});
	});

program.parse(process.argv);

if (!process.argv.slice(2).length) {
	program.outputHelp();
	return;
}