#!/usr/bin/env node

/*
 * CTWatch
 * Desc: Searches Certificate Transparency services for hostnames linked to certificates.
 * Author: Carey Li (https://github.com/cry)
 */

 "use strict";

let googleCT = require("./lib/ct/googleCT.js"),
	program = require('commander');

program
	.version('0.0.1')
	.option('-c, --ct-server <server>', 'specify which ct service to use (default Google)')
	.option('-f, --file <file>', 'save hostnames to file as JSON');

program
	.command('discover <hostname>')
	.description('scan Certificate Transparency logs for subdomains of hostname')
	.action((hostname) => {
		googleCT.getHostnames(hostname)
			.then((res) => {
				console.log("\nHostnames found: ");

				res.forEach((el) => console.log("> " + el));
			});
	});

program.parse(process.argv);

if (!process.argv.slice(2).length) {
	program.outputHelp();
	return;
}